/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gamezone;

import configuracion.configuracion;
import static configuracion.configuracion.idusuario;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author miguel
 */
public class frmLogin extends javax.swing.JFrame {

    Connection conexion;
    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        inicializaBaseDeDatos();
        setSize(450,230);
    }
    public void inicializaBaseDeDatos(){
        try{
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            conexion = DriverManager.
                    getConnection("jdbc:mysql://"
                    + "localhost/gamerzone","root","");
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblusuario = new javax.swing.JLabel();
        lblcontrasena = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnlogin = new javax.swing.JButton();
        lblpregunta = new javax.swing.JLabel();
        lbllogo = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblusuario.setText("Usuario");
        getContentPane().add(lblusuario);
        lblusuario.setBounds(21, 31, 87, 17);

        lblcontrasena.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblcontrasena.setText("Contraseña");
        getContentPane().add(lblcontrasena);
        lblcontrasena.setBounds(21, 69, 87, 22);

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(120, 20, 150, 30);

        btnlogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnloginMouseClicked(evt);
            }
        });
        getContentPane().add(btnlogin);
        btnlogin.setBounds(200, 120, 71, 25);

        lblpregunta.setForeground(new java.awt.Color(0, 0, 255));
        lblpregunta.setText("¿Aun no estas registrado?");
        lblpregunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpreguntaMouseClicked(evt);
            }
        });
        getContentPane().add(lblpregunta);
        lblpregunta.setBounds(10, 130, 160, 14);

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gamerzone/login.png"))); // NOI18N
        lbllogo.setText("jLabel3");
        getContentPane().add(lbllogo);
        lbllogo.setBounds(290, 10, 140, 140);
        getContentPane().add(txtContrasena);
        txtContrasena.setBounds(120, 60, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void lblpreguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpreguntaMouseClicked
        frmRegistro frmRegistro1 = new frmRegistro();
        frmRegistro1.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_lblpreguntaMouseClicked

    private void btnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseClicked
       try{
            PreparedStatement consulta = conexion.prepareStatement(""
                    + "SELECT * FROM usuarios WHERE gamertag=? AND contrasena=?");             
            consulta.setString(1,txtUsuario.getText());
            consulta.setString(2,txtContrasena.getText());
            ResultSet rs = consulta.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Bienvenido a la Gamer Zone");
                frmSeleccion frmSeleccion1 = new frmSeleccion();           
                frmSeleccion1.setVisible(true);
                configuracion.idusuario = rs.getInt("idusuario");
                this.dispose();
                
            }else{
                JOptionPane.showMessageDialog(null, "Usuario No Existe");
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }                                         
// TODO add your handling code here:
    }//GEN-LAST:event_btnloginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel lblcontrasena;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lblpregunta;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
