/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gamezone;

/**
 *
 * @author miguel
 */
public class frmRegistro extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistro
     */
    public frmRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtgamer = new javax.swing.JTextField();
        txtcrontrasena = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellidop = new javax.swing.JTextField();
        txtapellidom = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtregistrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("GamerTag");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 60, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 89, 60, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Apellido  Paterno");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 127, 106, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Apellido -Materno");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 160, 110, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("E-mail");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 200, 36, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Contraseña");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 51, 70, 15);

        txtgamer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgamerActionPerformed(evt);
            }
        });
        getContentPane().add(txtgamer);
        txtgamer.setBounds(120, 13, 184, 20);
        getContentPane().add(txtcrontrasena);
        txtcrontrasena.setBounds(120, 49, 184, 20);
        getContentPane().add(txtnombre);
        txtnombre.setBounds(120, 87, 184, 20);
        getContentPane().add(txtapellidop);
        txtapellidop.setBounds(120, 125, 184, 20);
        getContentPane().add(txtapellidom);
        txtapellidom.setBounds(120, 160, 180, 20);
        getContentPane().add(txtemail);
        txtemail.setBounds(120, 190, 184, 20);

        txtregistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtregistrar.setText("Registrar");
        txtregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(txtregistrar);
        txtregistrar.setBounds(210, 220, 89, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gamerzone/logo.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 30, 220, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtgamerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgamerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgamerActionPerformed

    private void txtregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtapellidom;
    private javax.swing.JTextField txtapellidop;
    private javax.swing.JTextField txtcrontrasena;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtgamer;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JButton txtregistrar;
    // End of variables declaration//GEN-END:variables
}
