/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gamezone;

import buscaminas.frmBuscaminas;
import javax.swing.JOptionPane;
import tictactoe.frmMenu;

/**
 *
 * @author miguel
 */
public class frmSeleccion extends javax.swing.JFrame {

    /**
     * Creates new form frmSeleccion
     */
    public frmSeleccion() {
        initComponents();
        setSize(530,400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbllogo1 = new javax.swing.JLabel();
        lbllogo2 = new javax.swing.JLabel();
        btngato = new javax.swing.JButton();
        btnbuscaminas = new javax.swing.JButton();
        btncombate = new javax.swing.JButton();
        btnRank = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gamerzone/gamer.jpg"))); // NOI18N
        getContentPane().add(lbllogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        lbllogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gamerzone/videogames.jpg"))); // NOI18N
        lbllogo2.setText("jLabel4");
        getContentPane().add(lbllogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 220));

        btngato.setBackground(new java.awt.Color(51, 51, 51));
        btngato.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btngato.setForeground(new java.awt.Color(0, 255, 204));
        btngato.setText("Tic-Tac-Toe");
        btngato.setMaximumSize(new java.awt.Dimension(141, 31));
        btngato.setMinimumSize(new java.awt.Dimension(141, 31));
        btngato.setPreferredSize(new java.awt.Dimension(141, 31));
        btngato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngatoActionPerformed(evt);
            }
        });
        getContentPane().add(btngato, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 230, 40));

        btnbuscaminas.setBackground(new java.awt.Color(51, 51, 51));
        btnbuscaminas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnbuscaminas.setForeground(new java.awt.Color(102, 102, 255));
        btnbuscaminas.setText("Buscaminas");
        btnbuscaminas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscaminasActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscaminas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 213, 230, 40));

        btncombate.setBackground(new java.awt.Color(51, 51, 51));
        btncombate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncombate.setForeground(new java.awt.Color(255, 0, 0));
        btncombate.setText("Combate Naval");
        btncombate.setMaximumSize(new java.awt.Dimension(141, 31));
        btncombate.setMinimumSize(new java.awt.Dimension(141, 31));
        btncombate.setPreferredSize(new java.awt.Dimension(141, 31));
        btncombate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncombateActionPerformed(evt);
            }
        });
        getContentPane().add(btncombate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 273, 230, 40));

        btnRank.setBackground(new java.awt.Color(0, 0, 0));
        btnRank.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRank.setForeground(new java.awt.Color(204, 0, 204));
        btnRank.setText("Ranking");
        btnRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankActionPerformed(evt);
            }
        });
        getContentPane().add(btnRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 40));

        lblfondo.setBackground(new java.awt.Color(0, 0, 0));
        lblfondo.setOpaque(true);
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscaminasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscaminasActionPerformed
        frmBuscaminas frmBuscaminas1 = new frmBuscaminas();
        frmBuscaminas1.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnbuscaminasActionPerformed

    private void btncombateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncombateActionPerformed
        JOptionPane.showMessageDialog(null, "El juego se encuentra actualmente fuera de sevicio Disculpe las molestias");
// TODO add your handling code here:
    }//GEN-LAST:event_btncombateActionPerformed

    private void btngatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngatoActionPerformed
        frmMenu frmMenu1 =new frmMenu();
        frmMenu1.setVisible(true);
        this.dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btngatoActionPerformed

    private void btnRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankActionPerformed
    frmRankings frmRanking1 = new frmRankings();
    frmRanking1.setVisible(true);
    this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnRankActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSeleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRank;
    private javax.swing.JButton btnbuscaminas;
    private javax.swing.JButton btncombate;
    private javax.swing.JButton btngato;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lbllogo1;
    private javax.swing.JLabel lbllogo2;
    // End of variables declaration//GEN-END:variables
}
