/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package juego.del.gato;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author FIMAZ
 */
public class frmTic extends javax.swing.JFrame implements  ActionListener{
    JButton[][] botones = new JButton[3][3];
    int turno = 1;
    Connection conexion;

    /**
     * Creates new form Ventana
     */
    public frmTic() {
        initComponents();
        this.setSize(415,400);
        panelTablero.setOpaque(false);
        crearTablero();
        inicializaBaseDeDatos();
        
    }
    public void crearTablero(){
        for(int fila=0; fila<3; fila++){
            for(int columna=0; columna<3; columna++){
                botones[fila][columna] = new JButton();
                botones[fila][columna].setBounds(78*columna, 78*fila, 78, 78);
                botones[fila][columna].addActionListener(this);
                panelTablero.add(botones[fila][columna]);
            }
        }
    }
    public void inicializaBaseDeDatos(){
        try{
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            conexion = DriverManager.
                    getConnection("jdbc:mysql://"
                    + "localhost/gamerzone","root","");
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJugador = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        panelTablero = new javax.swing.JPanel();
        btnReinicio = new javax.swing.JButton();
        lbllogo = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        lblJugador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblJugador.setForeground(new java.awt.Color(255, 0, 0));
        lblJugador.setText("Jugador 1");
        getContentPane().add(lblJugador);
        lblJugador.setBounds(130, 10, 130, 40);

        lblTurno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTurno.setForeground(new java.awt.Color(0, 153, 153));
        lblTurno.setText("Turno :");
        getContentPane().add(lblTurno);
        lblTurno.setBounds(20, 0, 100, 50);

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        getContentPane().add(panelTablero);
        panelTablero.setBounds(40, 70, 240, 230);

        btnReinicio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReinicio.setText("Reinicio");
        btnReinicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReinicioMouseClicked(evt);
            }
        });
        btnReinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnReinicio);
        btnReinicio.setBounds(300, 200, 100, 30);

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gamerzone/gamerbuscaminas.jpg"))); // NOI18N
        lbllogo.setText("jLabel1");
        getContentPane().add(lbllogo);
        lbllogo.setBounds(30, 300, 260, 60);

        lblfondo.setBackground(new java.awt.Color(0, 0, 0));
        lblfondo.setOpaque(true);
        getContentPane().add(lblfondo);
        lblfondo.setBounds(0, 0, 410, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinicioActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReinicioActionPerformed

    private void btnReinicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReinicioMouseClicked
        botones[0][0].setText(null);
        botones[0][1].setText(null);
        botones[0][2].setText(null);
        botones[1][0].setText(null);
        botones[1][1].setText(null);
        botones[1][2].setText(null);
        botones[2][0].setText(null);
        botones[2][1].setText(null);
        botones[2][2].setText(null);
        botones[0][0].setEnabled(true);
        botones[0][1].setEnabled(true);
        botones[0][2].setEnabled(true);
        botones[1][0].setEnabled(true);
        botones[1][1].setEnabled(true);
        botones[1][2].setEnabled(true);
        botones[2][0].setEnabled(true);
        botones[2][1].setEnabled(true);
        botones[2][2].setEnabled(true);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReinicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTic().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReinicio;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JPanel panelTablero;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void actionPerformed(ActionEvent e) {
        JButton boton = (JButton) e.getSource();
        if(turno==1){
            boton.setText("0");
            turno=0;
            lblJugador.setText("Invitado");
        }else{
            boton.setText("X");
            turno=1;
            lblJugador.setText("Jugador 1");
            
        }
        
        boton.setEnabled(false);
        revisaTablero();
         //To change body of generated methods, choose Tools | Templates.
    }
    void revisaTablero(){
        if(botones[0][0].getText() !=""){
        if(botones[0][0].getText() == botones[0][1].getText()
                && botones[0][1].getText() == botones[0][2].getText()
                ){
            juegoTerminado();
        }
       }
        if(botones[1][0].getText() !=""){
        if(botones[1][0].getText() == botones[1][1].getText()
                && botones[1][1].getText() == botones[1][2].getText()
                ){
            juegoTerminado();
        }
       }
        
       if(botones[2][0].getText() !=""){
        if(botones[2][0].getText() == botones[2][1].getText()
                && botones[2][1].getText() == botones[2][2].getText()
                ){
            juegoTerminado();
        }
       }       
       if(botones[0][0].getText() !=""){
        if(botones[0][0].getText() == botones[1][0].getText()
                && botones[1][0].getText() == botones[2][0].getText()
                ){
            juegoTerminado();
        }
       }       
       if(botones[0][1].getText() !=""){
        if(botones[0][1].getText() == botones[1][1].getText()
                && botones[1][1].getText() == botones[2][1].getText()
                ){
            juegoTerminado();
        }
       }       
       if(botones[0][2].getText() !=""){
        if(botones[0][2].getText() == botones[1][2].getText()
                && botones[1][2].getText() == botones[2][2].getText()
                ){
            juegoTerminado();
        }
       }    
       if(botones[0][0].getText() !=""){
        if(botones[0][0].getText() == botones[1][1].getText()
                && botones[1][1].getText() == botones[2][2].getText()
                ){
            juegoTerminado();
        }
       }       
       if(botones[0][2].getText() !=""){
        if(botones[0][2].getText() == botones[1][1].getText()
                && botones[1][1].getText() == botones[2][0].getText()
                ){
            juegoTerminado();
        }
       }   
       
    }
    void juegoTerminado(){
        botones[0][0].setEnabled(false);
        botones[0][1].setEnabled(false);
        botones[0][2].setEnabled(false);
        botones[1][0].setEnabled(false);
        botones[1][1].setEnabled(false);
        botones[1][2].setEnabled(false);
        botones[2][0].setEnabled(false);
        botones[2][1].setEnabled(false);
        botones[2][2].setEnabled(false);
        ImageIcon icon = new ImageIcon("src/Imagenes/carita.jpg");
        if(turno==1){
            JOptionPane.showMessageDialog(this, "Jugador 1 gano","Juego Terminado",JOptionPane.INFORMATION_MESSAGE,icon);
        }else{
            JOptionPane.showMessageDialog(this, "Jugador 2 gano","Juego Terminado",JOptionPane.INFORMATION_MESSAGE,icon);
        }
    }
}

